
<?php $this->headTitle('Edit Business - ' . $this->model->getCompany()) ?>

<?php
$form = $this->form;
?>
<div class="row">
    <form class="col-md-12 form form-horizontal" method="post" action="<?=$this->url('business/edit',[
        'business' => $this->model->getSlug(),
    ]) ?>">
        <fieldset>
            <legend>Edit Profile:</legend>
            <div class="row">
                <div class="col-sm-6">
                    <fieldset>
                        <legend>Details</legend>
                        <div class="form-group<?php if ($form->get('company')->getMessages()) echo ' has-error'; ?>">
                            <label class="col-md-4 control-label" for="company"><?=$form->get('company')->getLabel();?></label>
                            <div class="col-md-8">
                                <?=$this->formelement($form->get('company')); ?>
                                <span class="help-block">
                            <?=$this->formElementErrors($form->get('company'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                            </div>
                        </div>
                        <div class="form-group<?php if ($form->get('telephone')->getMessages()) echo ' has-error'; ?>">
                            <label class="col-md-4 control-label" for="telephone"><?=$form->get('telephone')->getLabel();?></label>
                            <div class="col-md-8">
                                <?=$this->formelement($form->get('telephone')); ?>
                                <span class="help-block">
                            <?=$this->formElementErrors($form->get('telephone'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                            </div>
                        </div>
                        <div class="form-group<?php if ($form->get('image')->getMessages()) echo ' has-error'; ?>">
                            <label class="col-md-4 control-label" for="image"><?=$form->get('image')->getLabel();?></label>
                            <div class="col-md-8">
                                <div class="input-group">
                                    <?=$this->formelement($form->get('image')); ?>
                                </span>
                                </div>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get('image'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                            </div>
                        </div>

                        <div class="form-group<?php if ($form->get('location')->getMessages()) echo ' has-error'; ?>">
                            <label class="col-md-4 control-label" for="location"><?=$form->get('location')->getLabel();?></label>
                            <div class="col-md-8">
                                <?=$this->formelement($form->get('location')); ?>
                                <span class="help-block">
                            <?=$this->formElementErrors($form->get('location'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                            </div>
                        </div>

                        <div class="form-group<?php if ($form->get('website')->getMessages()) echo ' has-error'; ?>">
                            <label class="col-md-4 control-label" for="website"><?=$form->get('website')->getLabel();?></label>
                            <div class="col-md-8">
                                <?=$this->formelement($form->get('website')); ?>
                                <span class="help-block">
                            <?=$this->formElementErrors($form->get('website'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                            </div>
                        </div>

                        <div class="form-group<?php if ($form->get('sector')->getMessages()) echo ' has-error'; ?>">
                            <label class="col-md-4 control-label" for="sector"><?=$form->get('sector')->getLabel();?></label>
                            <div class="col-md-8">
                                <?=$this->formelement($form->get('sector')); ?>
                                <span class="help-block">
                            <?=$this->formElementErrors($form->get('sector'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                            </div>
                        </div>
                    </fieldset>
                </div>

                <div class="col-md-6">
                    <fieldset>
                        <legend>HTML Content</legend>
                        <?=$this->formElement($form->get('text')); ?>
                    </fieldset>
                </div>
            </div>

            <?=$this->formHidden($form->get('businessListId')); ?>
            <?=$this->formHidden($form->get('slug')); ?>
            <?=$this->formHidden($form->get('userId')); ?>

            <input type="hidden" name="action" value="<?=$this->formAction; ?>">

            <div class="clearfix">&nbsp;</div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary"
                            data-loading-text="Please wait...">Submit</button>
                    <button type="button" class="btn btn-warning"
                            data-loading-text="Please wait..." onClick="window.location = '<?=$this->url('business',[
                        'business' => $this->model->getSlug(),
                    ]); ?>';">Cancel</button>
                </div>
            </div>
        </fieldset>
    </form>
</div>

<?=$this->textEditor()->summernote();?>
<?=$this->fileManager()->uploadButton('business-list-image', 'business-list-image-button');?>

