<?php $this->headTitle('Members') ?>

<?php if (count($this->models) > 0): ?>
    <div class="panel panel-default">
        <table class="table table-hover table-bordered table-condensed">
            <thead>
            <tr>
                <th data-field="businessListId">Business List Id</th>
                <th data-field="company">Company</th>
                <th data-field="dateCreated">Date Created</th>
                <th data-field="dateModified">Date Modified</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $row \UthandoBusinessList\Model\BusinessList */ ?>
            <?php foreach($this->models as $row): ?>
                <tr>
                    <td><?=$this->escapeHtml($row->getBusinessListId()); ?></td>
                    <td><?=$this->escapeHtml($row->getCompany()); ?></td>
                    <td><?=$this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
                    <td><?=$this->escapeHtml($this->formatDate($row->getDateModified())); ?></td>
                    <td>
                        <?=$this->partial('uthando-admin/partial/edit-actions', [
                            'pk'		=> 'businessListId',
                            'id'		=> $row->getBusinessListId(),
                            'tableName'	=> 'business-list',
                            'route'		=> 'admin/business-list/edit',
                        ]);?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?=$this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/business-list/page']
    ); ?>

<?php else: ?>
    <h4>There are no Members yet.</h4>
<?php endif; ?>