<?php $this->headTitle('View Businesses') ?>

<?=$this->partial('uthando-admin/partial/search', [
    'name'			=> 'business-list',
    'searchInputs'	=> [
        'Company' => 'company',
        'Sector' => 'sector',
    ],
]);?>

<?php /* @var $row \UthandoBusinessList\Model\BusinessList */ ?>
<?php foreach($this->models as $row):?>
<div class="media">
    <a class="pull-left" href="<?=$this->escapeHtml($row->getWebsite());?>">
        <img class="media-object" style="max-width:128px;" src="<?=$this->basePath('/userfiles/'.$this->escapeHtml
        ($row->getImage
        ()));?>"
             alt="<?=$this->escapeHtml($row->getCompany());?>">
    </a>
    <div class="media-body">
        <h4 class="media-heading">
            <a href="<?=$this->url('business', [
                'business'  => $row->getSlug(),
            ]);?>">
                <?=$this->escapeHtml($row->getCompany());?>
            </a>
        </h4>
        <?=$row->getText();?>
        <br>
        <i class="glyphicon glyphicon-tag"></i>&nbsp;<?=$this->escapeHtml($row->getLocation());?>&nbsp;
        <i class="glyphicon glyphicon-tag"></i>&nbsp;<?=$this->escapeHtml($row->getSector());?>
    </div>
</div>
<hr>
<?php endforeach;?>

<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
    ['route' => 'business-list/page']
); ?>