<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'UthandoBusinessList\Module'                      => __DIR__ . '/Module.php',
  'UthandoBusinessList\Controller\BusinessList'     => __DIR__ . '/src/UthandoBusinessList/Controller/BusinessList.php',
  'UthandoBusinessList\Event\ServiceListener'       => __DIR__ . '/src/UthandoBusinessList/Event/ServiceListener.php',
  'UthandoBusinessList\Form\BusinessList'           => __DIR__ . '/src/UthandoBusinessList/Form/BusinessList.php',
  'UthandoBusinessList\Hydrator\BusinessList'       => __DIR__ . '/src/UthandoBusinessList/Hydrator/BusinessList.php',
  'UthandoBusinessList\InputFilter\BusinessList'    => __DIR__ . '/src/UthandoBusinessList/InputFilter/BusinessList.php',
  'UthandoBusinessList\Mapper\BusinessList'         => __DIR__ . '/src/UthandoBusinessList/Mapper/BusinessList.php',
  'UthandoBusinessList\Model\BusinessList'          => __DIR__ . '/src/UthandoBusinessList/Model/BusinessList.php',
  'UthandoBusinessList\Service\BusinessList'        => __DIR__ . '/src/UthandoBusinessList/Service/BusinessList.php',
  'UthandoBusinessList\View\RecentBusinesses'       => __DIR__ . '/src/UthandoBusinessList/View/RecentBusinesses.php',
);
