<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-business-list/business-list/add'         => __DIR__ . '/view/uthando-business-list/business-list/add.phtml',
    'uthando-business-list/business-list/edit-business' => __DIR__ . '/view/uthando-business-list/business-list/edit-business.phtml',
    'uthando-business-list/business-list/edit'        => __DIR__ . '/view/uthando-business-list/business-list/edit.phtml',
    'uthando-business-list/business-list/index'       => __DIR__ . '/view/uthando-business-list/business-list/index.phtml',
    'uthando-business-list/business-list/list'        => __DIR__ . '/view/uthando-business-list/business-list/list.phtml',
    'uthando-business-list/business-list/business-form' => __DIR__ . '/view/uthando-business-list/business-list/business-form.phtml',
    'uthando-business-list/business-list/view-business' => __DIR__ . '/view/uthando-business-list/business-list/view-business.phtml',
    'uthando-business-list/business-list/view'        => __DIR__ . '/view/uthando-business-list/business-list/view.phtml',
);
